sudo: required
services:
  - docker

before_install:
  - docker build -t jonwehner/multi-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jonwehner/multi-react-test npm test

after_success:
  - docker build -t jonwehner/multi-client -f ./client/Dockerfile ./client
  - docker build -t jonwehner/multi-server -f ./server/Dockerfile ./server
  - docker build -t jonwehner/multi-worker -f ./worker/Dockerfile ./worker
  - docker build -t jonwehner/multi-nginx -f ./nginx/Dockerfile ./nginx
  - echo "$DOCKER_PASSWORD" docker login -u "$DOCKER_ID" --password-stdin
  - docker push jonwehner/multi-client
  - docker push jonwehner/multi-server
  - docker push jonwehner/multi-worker
  - docker push jonwehner/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-875014098063
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
