version: '3'
services:
  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  postgres: 
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /home/node/app/node_modules
      - /home/jon/studying/multi-container-test/server:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /home/node/app/node_modules
      - /home/jon/studying/multi-container-test/worker:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - /home/node/app/node_modules
      - /home/jon/studying/multi-container-test/client:/home/node/app
